// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.diploma.ccms.domain;

import com.diploma.ccms.domain.Messages;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Messages_Roo_Configurable {
    
    declare @type: Messages: @Configurable;
    
}
