// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.diploma.ccms.domain;

import com.diploma.ccms.domain.Messages;
import com.diploma.ccms.domain.MessagesDataOnDemand;
import com.diploma.ccms.domain.MessagesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MessagesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MessagesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MessagesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MessagesIntegrationTest: @Transactional;
    
    @Autowired
    private MessagesDataOnDemand MessagesIntegrationTest.dod;
    
    @Test
    public void MessagesIntegrationTest.testCountMessageses() {
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", dod.getRandomMessages());
        long count = Messages.countMessageses();
        Assert.assertTrue("Counter for 'Messages' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MessagesIntegrationTest.testFindMessages() {
        Messages obj = dod.getRandomMessages();
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Messages' failed to provide an identifier", id);
        obj = Messages.findMessages(id);
        Assert.assertNotNull("Find method for 'Messages' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Messages' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MessagesIntegrationTest.testFindAllMessageses() {
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", dod.getRandomMessages());
        long count = Messages.countMessageses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Messages', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Messages> result = Messages.findAllMessageses();
        Assert.assertNotNull("Find all method for 'Messages' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Messages' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MessagesIntegrationTest.testFindMessagesEntries() {
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", dod.getRandomMessages());
        long count = Messages.countMessageses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Messages> result = Messages.findMessagesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Messages' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Messages' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MessagesIntegrationTest.testFlush() {
        Messages obj = dod.getRandomMessages();
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Messages' failed to provide an identifier", id);
        obj = Messages.findMessages(id);
        Assert.assertNotNull("Find method for 'Messages' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMessages(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Messages' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessagesIntegrationTest.testMergeUpdate() {
        Messages obj = dod.getRandomMessages();
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Messages' failed to provide an identifier", id);
        obj = Messages.findMessages(id);
        boolean modified =  dod.modifyMessages(obj);
        Integer currentVersion = obj.getVersion();
        Messages merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Messages' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessagesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", dod.getRandomMessages());
        Messages obj = dod.getNewTransientMessages(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Messages' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Messages' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Messages' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MessagesIntegrationTest.testRemove() {
        Messages obj = dod.getRandomMessages();
        Assert.assertNotNull("Data on demand for 'Messages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Messages' failed to provide an identifier", id);
        obj = Messages.findMessages(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Messages' with identifier '" + id + "'", Messages.findMessages(id));
    }
    
}
