// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.diploma.ccms.domain;

import com.diploma.ccms.domain.Messages;
import com.diploma.ccms.domain.MessagesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MessagesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MessagesDataOnDemand: @Component;
    
    private Random MessagesDataOnDemand.rnd = new SecureRandom();
    
    private List<Messages> MessagesDataOnDemand.data;
    
    public Messages MessagesDataOnDemand.getNewTransientMessages(int index) {
        Messages obj = new Messages();
        setText(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void MessagesDataOnDemand.setText(Messages obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public void MessagesDataOnDemand.setTitle(Messages obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Messages MessagesDataOnDemand.getSpecificMessages(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Messages obj = data.get(index);
        Long id = obj.getId();
        return Messages.findMessages(id);
    }
    
    public Messages MessagesDataOnDemand.getRandomMessages() {
        init();
        Messages obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Messages.findMessages(id);
    }
    
    public boolean MessagesDataOnDemand.modifyMessages(Messages obj) {
        return false;
    }
    
    public void MessagesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Messages.findMessagesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Messages' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Messages>();
        for (int i = 0; i < 10; i++) {
            Messages obj = getNewTransientMessages(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
